INSERT INTO BLC_DATA_DRVN_ENUM (ENUM_ID, ENUM_KEY, MODIFIABLE) VALUES (1, 'layout_type', FALSE);

INSERT INTO BLC_DATA_DRVN_ENUM_VAL (ENUM_VAL_ID, DISPLAY, HIDDEN, ENUM_KEY, ENUM_TYPE) VALUES (1, 'GRID_9', FALSE, 'GRID_9', 1);

INSERT INTO BLC_DATA_DRVN_ENUM_VAL (ENUM_VAL_ID, DISPLAY, HIDDEN, ENUM_KEY, ENUM_TYPE) VALUES (2, 'GRID_16', FALSE, 'GRID_16', 1);

INSERT INTO BLC_DATA_DRVN_ENUM_VAL (ENUM_VAL_ID, DISPLAY, HIDDEN, ENUM_KEY, ENUM_TYPE) VALUES (3, 'LIST', FALSE, 'LIST', 1);