INSERT INTO BLC_DATA_DRVN_ENUM (ENUM_ID, ENUM_KEY, MODIFIABLE) VALUES (1, 'layout_type', FALSE);

INSERT INTO BLC_DATA_DRVN_ENUM_VAL (ENUM_VAL_ID, DISPLAY, HIDDEN, ENUM_KEY, ENUM_TYPE) VALUES (1, '9宫格', FALSE, 'GRID_9', 1);

INSERT INTO BLC_DATA_DRVN_ENUM_VAL (ENUM_VAL_ID, DISPLAY, HIDDEN, ENUM_KEY, ENUM_TYPE) VALUES (2, '16宫格', FALSE, 'GRID_16', 1);

INSERT INTO BLC_DATA_DRVN_ENUM_VAL (ENUM_VAL_ID, DISPLAY, HIDDEN, ENUM_KEY, ENUM_TYPE) VALUES (3, '列表', FALSE, 'LIST', 1);